### ISSUE TITLE
2step otp problem when new user activation

### ISSUE THREAD

**Issue by santhoshmohan** [jeremykenedy/laravel-auth#105]
When 2step auth is turned on, once we click the activation link(new user registration)...it asks for 2nd factor OTP but the OTP is not actually sent and we will get an error(refer pic-error.jpg) if we click "didn't receive the code" link. Everything is fine if we set 2step auth = false in .env file 
![error](https://user-images.githubusercontent.com/8510423/35554193-d90ec9f8-05c0-11e8-886b-78acdacec8f0.jpg)

**Comment by jeremykenedy** [comment]
That is caused by this line https://github.com/jeremykenedy/laravel2step/blob/master/src/app/Http/Middleware/Laravel2step.php#L31 in the laravel2step package. The register route is excluded from the middleware. This is due to laravel redirecting to login registration without email verification. When time allows I need to adjust the laravel2step project to facilitate the register as an option with the additional ability to in laravel-auth to add the verification notification to the registration confirmation email. I am not sure how to handle one email to confirm the account followed by another to verify the login. 

Please let me know your thoughts and suggestions :)
