### ISSUE TITLE
Is it possible for new user registering to be defaulted as admins and have their own dashboard

### ISSUE THREAD

**Issue by AlexFoster009** [jeremykenedy/laravel-auth#146]
Hello, i am curious if i am able to set up the registration so that when a user signs up and activates they default as admins with their own instance of the dashboard in which they can add users to be associated with their account. I couldnt find where to change the default role, or where the role is being set even

Thanks in advance

**Comment by jeremykenedy** [comment]
Hi Alex,

The role is assigned in the method: `activate($token)` here https://github.com/jeremykenedy/laravel-auth/blob/master/app/Http/Controllers/Auth/ActivateController.php#L137 Then updated with the lines:
https://github.com/jeremykenedy/laravel-auth/blob/master/app/Http/Controllers/Auth/ActivateController.php#L158 and
https://github.com/jeremykenedy/laravel-auth/blob/master/app/Http/Controllers/Auth/ActivateController.php#L159

The initial role when a user is created is done with these lines: 
https://github.com/jeremykenedy/laravel-auth/blob/master/app/Http/Controllers/Auth/RegisterController.php#L103
https://github.com/jeremykenedy/laravel-auth/blob/master/app/Http/Controllers/Auth/RegisterController.php#L116

I really need to fix that files doc blocks.

You may want to consider updating the seed https://github.com/jeremykenedy/laravel-auth/blob/master/database/seeds/RolesTableSeeder.php to have some sort of "super admin" role in order to manage all the "admin". And then sprinkle all the logic needed throughout the app :)

Thanks for checking out the project.

**Comment by AlexFoster009** [comment]
Is there a way I can make a clean instance of the dashboard for each admin to create their own users instead of pooling them all together?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jeremykenedy** [comment]
Current logic only separates out between the 2 types: user and admin. It would need a feature/refactored to have each individual user have their own dashboards.

**Comment by AlexFoster009** [comment]
Any suggestions or things you could point me to to achieve this? :)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by kennethkaane** [comment]
What you are looking for is called multi-tenancy. Check out this project https://laravel-tenancy.com. Yes, it would be great if this was included into laravel-auth.
