### ISSUE TITLE
Permissions and Roles

### ISSUE THREAD

**Issue by MACscr** [jeremykenedy/laravel-auth#149]
Not sure if this question should go here or under your laravel-roles project, but since it came with this one, im going to do it here.

I have 3 role types right now, Admins, Providers, Members.

Right now I have a user that has a role of Provider and in the database table permission_role, the role id 4 (providers) has a permission_id of 2 assigned to it. According to the permissions table, this should allow users with the providers role to be able to create accounts. When I try to go to /users/create though, it says its forbidden. Any ideas why that might be?

Trying to wrap my head around all the permissioning with this project has been a bit tough as I am not sure much the laravel-roles docs really apply to the laravel-auth repo. Thanks for your time, I really appreciate all that you do!

**Comment by PrimeGhostDE** [comment]
I do select my permissions by slug. Please be aware, that only lower case is supported.
I did not try to check by ids before. Maybe there is some other, who can help.

But if you are using laravel auth as mentioned. You can check everything with Auth::user()->haspermission(slug)

Or in blade using @permission

If you want to check one out of many, you can concat your slugs by pipe as seperator.

I hope that helps.

There are permissions owned by role, which will match most of your cases. But some users may need more rights as roles may offer.
I didnt had this problem since now. So I cannot say, the customized permissions per user do work. But I would say so.
Please check your code concerning your permissionschecks. I think there is the problem. Had mine too as I used this repository first.

Hope that helps.
Prime :)

**Comment by MACscr** [comment]
Jeremy, thanks for the quick reply!

I dont see a role:admin check in the web.php. Also, whats the point of the db permission assignment that is there by default in your seeds with your project if that is not queried during the perm check? Am I missing something?

**Comment by jeremykenedy** [comment]
In response to "I dont see a role:admin check in the web.php"

See the above comment: "ou may be getting a 403 if because of the middleware called in web.php#L99"

**Comment by MACscr** [comment]
Thanks, no idea how i missed that when i searched and I somehow didnt see your line reference either. Any feedback on my comment about the db entries? Id really love to know how to properly use that.

**Comment by MACscr** [comment]
Ah, I guess I would use something more like:

`Route::group(['middleware' => ['auth', 'activated', 'permission:create.users', 'activity', 'twostep']], function () {`

I guess i need to look at this closer as obviously I wouldnt want to set such a permission for that entire block. Would need something a bit more granular so that it when applying such permission, it really only did apply to the create users method and not that whole section. hmm.

**Comment by goodmuyis** [comment]
Nice to see this on time
