### ISSUE TITLE
Error after submitting registration

### ISSUE THREAD

**Issue by Marcosul** [jeremykenedy/laravel-auth#23]
After submitting the registration, there is an error on the screen / activate.

What could be happening?

Thak you!

Error Printscreen
![activate](https://cloud.githubusercontent.com/assets/4714018/24770908/f543047e-1ae1-11e7-8efc-fb3f2d33e216.png)

**Comment by jeremykenedy** [comment]
Hi, 

Thank you for checking out the repo.

I have corrected the issue that was causing this, if you do a pull it will not work. I needed to add in an additional check to see if a profile exists in the app.blade.php and nav.blade.php.

This was happening after registration because users that register via email's profiles are created once they confirm their email.

The issue has been resolved, please let me know if you have any further issues.

Thank you for reporting this,

Jeremy
