### ISSUE TITLE
Invalid .env

### ISSUE THREAD

**Issue by VSG24** [jeremykenedy/laravel-auth#235]
String values must be escaped by double quotes.

**Comment by jeremykenedy** [comment]
Hmmm, I have not encountered this.

**Comment by jeremykenedy** [comment]
Can you give an example

**Comment by VSG24** [comment]
I'm on Windows (Git Bash) and followed the installations instruction and faced this error:

`Dotenv values containing spaces must be surrounded by quotes.`

Fixed it by surrounding all long strings with double quotes.

For example I changed (taken from your repo `.env.example`):

```
EMAIL_EXCEPTION_FROM=email@email.com
EMAIL_EXCEPTION_TO='email1@gmail.com, email2@gmail.com'
```

into:

```
EMAIL_EXCEPTION_FROM="email@email.com"
EMAIL_EXCEPTION_TO="email1@gmail.com, email2@gmail.com"
```

**Comment by jeremykenedy** [comment]
It could be an environment issue, I have this working on multiple production systems and my local and do not have this issue.

**Comment by seanmlonergan** [comment]
Failed to parse dotenv file due to an unexpected escape sequence. Failed at ['App\Models\User'].
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1 

I got this installing today on Ubuntu environment, updated App\Model\User to not have single quotes and worked fine. Also env issue?

**Comment by jeremykenedy** [comment]
This was just fixed. Thanks,

**Comment by seanmlonergan** [comment]
This product was just what I was looking for, hope to become a contributor down the road but we'll see. Still learning alot. Thanks so much for quick response, great work!
