### ISSUE TITLE
is it possible for new user registering with specified user role?

### ISSUE THREAD

**Issue by furkanpamukcular** [jeremykenedy/laravel-auth#299]
hello,

i wonder is it possible for new user registering with specified user role with form element at register.blade.php file. i want user chose the role while they are signing up.

Thanks in advance.

**Comment by jeremykenedy** [comment]
Hi,

Out of the box, no.

Currently, when they register and are not using SSO they get the `unverified` role attached, see: https://github.com/jeremykenedy/laravel-auth/blob/master/app/Http/Controllers/Auth/RegisterController.php#L103

You can add in another form in the activation message once they confirm their account to update their roles. It would take a little work but it can be done.

You would have to do the following:
1. Create the form and send it the roles you want them to have access to.
2. Create a route to process and handle the form.
3. Add in validation that also only allows the roles you sent it otherwise they may be able to break the roles.
4. Sync new roles.
5. Redirect to next desired page.
