### ISSUE TITLE
reset password issue

### ISSUE THREAD

**Issue by peacewalkers** [jeremykenedy/laravel-auth#398]
**First, take look at:**
1. https://github.com/jeremykenedy/laravel-auth#opening-an-issue
2. https://github.com/jeremykenedy/laravel-auth/issues?q=is%3Aissue+is%3Aclosed

**Did you star the repo?**
Yes

**Describe the bug**
While trying to reset the password, when you click on the reset password link received through email. In the form for input field email instead of showing the actual email address, it is only showing as 1.

**To Reproduce**
1. go to password reset URL
2. Enter the email address you want to reset and submit to receive reset email instructions.
3. Click on the "reset password" button or URL mentioned in the email to reset/enter a new password.
4. in the reset password page for email input it shows "1" instead of displaying the actual email address.

**Expected behavior**
Display of actual user email address for which the password is being reset.

**Screenshots**
![image](https://user-images.githubusercontent.com/29300526/128230599-f92ec27e-659f-478d-9fb9-451afbb0e5c0.png)

**Comment by goodmuyis** [comment]
Are you sure you are using the `view blade` that came with this package and you have not made any strange changes to it

**Comment by peacewalkers** [comment]
No, I have not made any changes. I am sure you will be able to reproduce the error

**Comment by goodmuyis** [comment]
> No, I have not made any changes. I am sure you will be able to reproduce the error

I just figure out what your issue is. Go to [line 26 of reset.blade.php](https://github.com/jeremykenedy/laravel-auth/blob/e9fb8667291c2ca1983718263aca1e6c00ac3640/resources/views/auth/passwords/reset.blade.php#L25)   ../resources/views/auth/passwords/reset.blade.php

Change the input field value from `value="{{ $email or old('email') }}"` to `value="{{ $email ?? old('email') }}"` replacing the **or**  with **??**. That should fix the problem

@jeremykenedy kindly edit the file to fix the issue. Thanks
