### ISSUE TITLE
Admin profile return 404

### ISSUE THREAD

**Issue by Domeman** [jeremykenedy/laravel-auth#53]
I did a fresh install. login as Admin and select profile I get error 404. The user works fine.
I created a new admin user and can see his profile. 
Is there a setting missing when the admin user is created.
Thanks.

**Comment by jeremykenedy** [comment]
Hello,
I just did a fresh install and all worked good.
I created an additional user with admin privileges and was able to view their profile.
I logged out and logged in as the admin user I created and was able to view and edit the profile.
I cannot duplicate.

**Comment by Domeman** [comment]
I am using windows 10. Don't think it matters. 
Figured it out. shawna.jerde with the period cause 404 not found 
shawnajerde with out the period works.

**Comment by jeremykenedy** [comment]
I am thinking this might be an environment issue with how your sites-enabled is configured with nginx.  I am using a laravel homestead instance for development and and not getting this issue. I just tested it with putting `shawna.jerde` (full local url `http://laravel-auth.local/profile/shawna.jerde`) and it tested ok.

**Comment by Domeman** [comment]
Tried to send you a message thru gihub didn't work.

Trying your laravel user/Admin. Should I send a question here or on submit an issue? When I click login and the page comes up and I don't login. Then I fill in the information and try to login and it fails because the tokens has expired. Is there a graceful way to handle that with out getting a page full of errors.

Thanks,
Roger

**Comment by jeremykenedy** [comment]
This is also an environment issue. The CSFR is being triggered.
Currently, there is not a way to handle this environment error elegantly and is a tough issue to solve because it is external to the codebase and is the environment. 

I have researched into Laravel 5.5 and they are planning on having a way to handle this a little better. Here is more info on that upcoming Laravel change: https://laracasts.com/series/whats-new-in-laravel-5-5/episodes/2

**Comment by CharlesKumar** [comment]
It's probably due to the php environment issue, actually it was reported as photo bug [doturlbug](https://bugs.php.net/bug.php?id=61286)

In Windows php built in server runs with the help of MSVC 
See [here](https://wiki.php.net/internals/windows/compiler)

[Discussion](https://github.com/slimphp/Slim/issues/359) in slim php

May be compiler, serverAPI in phpinfo() can give more info than just windows
