### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by aarontanzk** [jeremykenedy/laravel-auth#86]
Hi I did a git clone with all the steps followed.

Currently stuck with this problem:

Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required "

**Comment by aarontanzk** [comment]
At register.php

**Comment by aarontanzk** [comment]
and how do I disable email verification?

**Comment by aarontanzk** [comment]
Much thanks for this great repo!

**Comment by aarontanzk** [comment]
ok, disabled mail.

1)when i register as a user and click on Profile, this error shows up 
ErrorException (E_NOTICE)Trying to get property of non-object
 
2) how does the user edit profile? doesnt seem to be a link available on the user dashboard to do so

**Comment by jeremykenedy** [comment]
That is due to the user profile being created upon email verification. You will need to move look at the method called when confirming the account via email and extract that portion that creates the user a profile and add that to the register controller.

The design was not to have a user profile created until the account is verified, so in some revisions will need to be put in place to change that.

**Comment by jeremykenedy** [comment]
Here is where the profile gets created: https://github.com/jeremykenedy/laravel-auth/blob/master/app/Http/Controllers/Auth/ActivateController.php#L138
